knock knock easter egg
Yes-Theory-Fam/yesbot-ts pull request #164
Opened 2020-11-01 20:19 UTC by huffle67

bot says "who's there? 👀" when you type !voice knock knock in #bot-commands channel
hehe
except i forgot a } at the end of the lines i added but idk how to edit it so i'm just sending a pull request without it cause coding is hard and i'm tired

2020-11-01 20:33 UTC, geisterfurz007 requested changes
When #161 is merged, this would cause both "Who's there? 👀" as well as "You have to ping the user you want to join!"

This PR should either wait for #161 or work on the feat/voice-knock branch.

2020-11-01 20:34 UTC, huffle67 commented
that sounds like a you problem and not a me problem smh

2020-11-01 20:56 UTC, shagunmistry submitted a review, later dismissed

2021-01-03 14:28 UTC, geisterfurz007 commented
Stale for two months; closing

2021-01-03 14:28 UTC, closed without merging