fix: issue #223
Yes-Theory-Fam/yesbot-ts pull request #225
Opened 2021-05-03 20:55 UTC by hasanlatch007

Testing:

Tested users currently in a game and if they can be invited by user C, the double-check for issue #223 basically
Tested users cannot be invited to a new game if on the configuration page

Implementation:

In file: GameHub.ts, added the if to check if cleanPlayers is bigger or equal to the minimum of players required before starting the game.
In these files: GameHub.ts, GameSession.ts, and Spyfall.ts. Added the new property called Configuration. Basically split the patch config to avoid users being invited to a new game while on the configuration page of the game.

2021-05-05 15:09 UTC, geisterfurz007 requested changes

2021-05-05 15:09 UTC, geisterfurz007 commented on src/games/GameHub.ts
> +    if (cleanedPlayers.length >= clazz.config.minPlayers) {
Invert the if to reduce nesting (so `if (cleanedPlayers.length < clazz.config.minPlayers) { /* send message and return */ }`)

2021-05-05 15:09 UTC, geisterfurz007 commented on src/games/GameSession.ts
> +  public async Configuration(
Function names should start with a lowercase letter. This function doesn't have to be async. Also just configuration is quite vague, how about
```suggestion
  public setBaseConfiguration(
```
The return type would then just be `void`.

2021-05-05 15:29 UTC, hasanlatch007 commented on src/games/GameHub.ts
> +    if (cleanedPlayers.length >= clazz.config.minPlayers) {
Okay, what should I set the send message as?

2021-05-05 15:37 UTC, geisterfurz007 commented on src/games/GameHub.ts
> +    if (cleanedPlayers.length >= clazz.config.minPlayers) {
With the same one that we use already a little further up in the code:

https://github.com/Yes-Theory-Fam/yesbot-ts/blob/09c02cb4df4b2661039d3a766b6373e8b8287aba/src/games/GameHub.ts#L260

2021-05-05 15:39 UTC, hasanlatch007 commented on src/games/GameHub.ts
> +    if (cleanedPlayers.length >= clazz.config.minPlayers) {
Oki used the right one sending it your way!

2021-05-05 17:33 UTC, hasanlatch007 commented
Also on the GameHub.ts I changed the variables to the top of the if at line 285 to make it look better and neattier

2021-05-06 15:36 UTC, geisterfurz007 requested changes

2021-05-06 15:36 UTC, geisterfurz007 commented on src/games/GameHub.ts
> +    const minPlayers = clazz.config;
This is incorrect. Either: `const minPlayers = clazz.config.minPlayers;` or `const { minPlayers } = clazz.config;` would work however.

2021-05-06 15:36 UTC, geisterfurz007 commented on src/games/GameHub.ts
> +    if (cleanedPlayers.length < clazz.config.minPlayers) {
Since you extracted minPlayers to a variable, you can use it here as well:
```suggestion
    if (cleanedPlayers.length < minPlayers) {
```

2021-05-06 15:56 UTC, hasanlatch007 commented
Should be fixed now!

2021-05-06 16:53 UTC, hasanlatch007 commented
Tested it, it does delete the channel after 60 seconds and now the message is sent in #bot-games

2021-05-06 17:44 UTC, geisterfurz007 approved these changes

2021-05-06 17:44 UTC, merged