setup jest with first basic jest tests
Yes-Theory-Fam/yesbot-ts pull request #237
Opened 2021-05-21 23:41 UTC by adrian-goe

- setup jest for https://github.com/Yes-Theory-Fam/yesbot-ts/issues/235
- add first tests

2021-05-22 08:25 UTC, adrian-goe commented
https://github.com/Yes-Theory-Fam/yesbot-ts/issues/235

2021-05-22 13:49 UTC, geisterfurz007 commented
After the additions from #231, the tests don't run anymore since jest cannot resolve type-graphql anymore. I just published `@yes-theory-fam/database@0.4.4` that allows direct referencing of the client through the import `@yes-theory-fam/database/client`. Replacing all `@yes-theory-fam/database` imports with that makes jest run as expected.

2021-05-22 13:59 UTC, geisterfurz007 requested changes
Other things:

 - Files are not formatted with prettier
 - The test never terminates and appears to hang infinitely, not sure about the cause here

2021-05-22 13:59 UTC, geisterfurz007 commented on __tests__/common/CustomMethods.spec.ts
> +  } as unknown) as Message;
This might be worth extracting to a function with a few arguments for things like author, content and cleanContent, since it's already duplicated a little further below.

2021-05-22 13:59 UTC, geisterfurz007 commented on __tests__/common/CustomMethods.spec.ts
> +      id: 312297787901607937,
It doesn't matter much but I think this could be a more generic ID

2021-05-22 13:59 UTC, geisterfurz007 commented on jest.config.js
> +  testEnvironment: 'node',
`__tests__/mocks/index.ts` was picked up as a testfile and jest complained that there was no test in it.
`modulePathIgnorePatterns: ["<rootDir>/__tests__/mocks"],` in here excludes the mocks.

2021-05-22 18:41 UTC, adrian-goe commented on __tests__/common/CustomMethods.spec.ts
> +  } as unknown) as Message;
No, I wouldn't move this to a function, because the mocks are built specifically for the tests. That would mean a lot more effort.

2021-05-22 19:33 UTC, adrian-goe commented
> * The test never terminates and appears to hang infinitely, not sure about the cause here
I'm trying to find a solution for that. But currently I dont find where the `DiscordjsError: Request to use token, but token was unavailable to the client.` is thrown, because the test is successful. But I will look further into this.

2021-06-19 15:26 UTC, adrian-goe commented
did a new PR for the new structure (https://github.com/Yes-Theory-Fam/yesbot-ts/pull/278) so this will be closed.

2021-06-19 15:26 UTC, closed without merging