Creat dockerimage
Yes-Theory-Fam/yesbot-ts pull request #264
Opened 2021-06-16 19:25 UTC by adrian-goe

#254 
Create the Dockerfile
net step would be to create the pipline for this

2021-06-17 09:02 UTC, geisterfurz007 requested changes

2021-06-17 09:02 UTC, geisterfurz007 commented on docker-compose.yml
> +      PRISMA_DATABASE_URL: "postgresql://yesbot:yesbot@yesbot-ts_postgres_1:5432/yesbot?schema=public"
We should probably use env variables for this, then we can still configure these on the server.

2021-06-17 09:02 UTC, geisterfurz007 commented on tsconfig.json
> +    /* Disallow inconsistently-cased references to the same file. */
The comments here moved around due to formatting and describe the things above them.

2021-06-17 09:02 UTC, geisterfurz007 commented on package.json
> +    "@tsconfig/node14": "1.0.1",
This isn't used (if I understand correctly)

2021-06-19 12:45 UTC, adrian-goe commented on docker-compose.yml
> +      - postgres
Why should I have to specify a version? Postgres is using version 13 and yes bot is using the latest one that will be deployed in GitHub Container Registry.

I can create a seperat file.
But if you only want to have the database, you can run `docker-compose up -d postgres` this starts just the posgres container

2021-06-19 13:08 UTC, adrian-goe commented on tsconfig.json
> +    /* Disallow inconsistently-cased references to the same file. */
I would remove them all. The docs are good enogh. 🙈

2021-06-19 13:09 UTC, geisterfurz007 commented on docker-compose.yml
> +      - postgres
In development you will almost always want just the database so I thought it made sense to have that as default. Then again it's true, it's just one more word. This would require an update in the [CONTRIBUTING.md](https://github.com/Yes-Theory-Fam/yesbot-ts/blob/master/CONTRIBUTING.md#run-the-database) then.

2021-06-19 13:10 UTC, geisterfurz007 commented on tsconfig.json
> +    /* Disallow inconsistently-cased references to the same file. */
👍

2021-06-19 13:18 UTC, adrian-goe commented on docker-compose.yml
> +      - postgres
I updated the CONTRIBUTING.md 👍🏻

2021-06-19 13:19 UTC, geisterfurz007 approved these changes

2021-06-19 13:19 UTC, geisterfurz007 commented
LGTM!

2021-06-19 13:19 UTC, merged