Feature/deadchat for groups
Yes-Theory-Fam/yesbot-ts pull request #289
Opened 2021-06-21 15:41 UTC by hasanlatch007

Also includes deleting `.npmrc` file, uses the same function as !group changeCooldown for moderations.
Pretty straight forward, reminder to merge the db update so you don't get a bunch of red lines :)!

2021-06-21 15:43 UTC, hasanlatch007 commented
closes #142

2021-06-21 16:18 UTC, geisterfurz007 requested changes

2021-06-21 16:18 UTC, geisterfurz007 commented on src/programs/deadchat-groups.ts
> +import { Message } from "discord.js";
Technically this file doesn't contain a single program. It should either be moved to group-manager.ts or a new group-manager folder should be created to hold everything relevant to groups.

2021-06-21 16:18 UTC, geisterfurz007 commented on src/programs/deadchat-groups.ts
> +export const deadchatGroup = async (
The name is not ideal. It returns whether a chat is dead enough for a group so something like `isChatDeadForGroup` or `isChatDead` would be a better fit (this includes the filename as well).

2021-06-21 16:18 UTC, geisterfurz007 commented on src/programs/deadchat-groups.ts
> +};
The side-effects in this function are not ideal. The only thing changing in this large block is the output based on the time remaining till dead. Maybe instead of a boolean + side-effects, this function could return the remaining minutes or seconds till the chat would be dead and the side-effects happen at the callsite of this? In this case the name should be changed as well (ignoring my earlier comment).

The text could be boiled down to \`Chat is not dead! You can ping this group in the next ${timeRemainingString}\` to avoid repetitions (and sneaky bugs where the error happens twice which happens to be the case here if `timeRemaining === 1` as there is no return after it ;) ).

2021-06-21 16:18 UTC, geisterfurz007 commented on src/programs/group-manager.ts
> +    "856479423490031640", // chat-too
The ID should not be changed.

2021-06-21 16:19 UTC, geisterfurz007 requested changes
Update `@yes-theory-fam/database` to `0.6.1` which contains the deadtime field on UserGroup.

2021-06-21 19:52 UTC, findtravishere commented on src/programs/group-manager.ts
> +    const timeRemaningforDeadchat = await isChatDead(message, group.name)
`timeRemainingForDeadchat`

2021-06-21 20:11 UTC, hasanlatch007 commented
Updated my typo :'). Did not go for seconds the idea of it saying `1 minutes` does bother me but it is what it is, code works as functioned hopefully my variable names are creative enough for this one :')

2021-06-21 20:34 UTC, geisterfurz007 requested changes

2021-06-21 20:34 UTC, geisterfurz007 commented on src/programs/group-manager.ts
> +    if (timeRemainingForDeadchat >= group.deadtime) {
I might be incorrect because it's late but I believe this is wrong. `timeRemainingForDeadchat` contains the time chat needed to be dead for to allow a ping. So any value **greater than 0** means the ping is not allowed, not any value greater than the group's dead time.

Given that `timeRemainingForDeadchat` is (essentially) guaranteed to be less than `group.deadtime` (since the function subtracts from it), this is never true, is it? I will try this out tomorrow when I am not 30 minutes late to sleep and report back.

2021-06-21 20:34 UTC, geisterfurz007 commented on src/programs/group-manager.ts
> +const isChatDead = async (
The function name isn't accurate anymore since it doesn't return a boolean but a number.

2021-06-21 20:34 UTC, geisterfurz007 commented on src/programs/group-manager.ts
> +  });
You can save the additional database query by passing in the group instead of the group name.

2021-06-21 20:57 UTC, hasanlatch007 commented on src/programs/group-manager.ts
> +const isChatDead = async (
damn I just saw this after committing :')

2021-06-21 21:23 UTC, hasanlatch007 commented on src/programs/group-manager.ts
> +    if (timeRemainingForDeadchat >= group.deadtime) {
For example, let's take this if `deadtime` is equal to 5, and `Date. now()` is bigger than the last messages send `timeDifference` will be a positive number if it's bigger than the deadtime, `timeRemaining` will return a negative number.
Resulting in the chat being able to be pinged, testing went well for this, but I could have my math wrong for this, so I won't commit anymore before you've checked it.

2021-06-27 14:25 UTC, geisterfurz007 commented on src/programs/group-manager.ts
> +    if (timeRemainingForDeadchat >= group.deadtime) {
I double checked this and it seems broken indeed; to reproduce:

1. Create a new group
2. Set the deadtime to 15 minutes
3. Send a message in #music in the hobbies section
4. Wait 3 minutes
5. Ping the group

Expected: The chat is not dead (since you pinged it 3 minutes ago) so there is no ping
Actual: The group is pinged.

`if (timeRemainingForDeadchat > 0) {` appears to work as intended though!

2021-07-01 16:26 UTC, geisterfurz007 commented
@yes-theory-fam/database still needs to be updated to 0.6.1 if I am not mistaken

2021-07-02 14:53 UTC, geisterfurz007 commented on src/programs/group-manager.ts
> +  return deadTime - Math.round(timeDifference);
This might be picky but I found this hard-ish to read. Instead of defaulting to deadTime for the case lastMessages.length is *not* 2 to then return deadTime - deadTime later, it would be more straightforward to just return 0 in that case:

```ts
if (lastMessages.length < 2) {
  return 0;
}

const timeDifference = (Date.now() - lastMessages[1].createdTimestamp) / 1000 / 60;
return deadTime - Math.round(timeDifference);
```

2021-07-02 14:57 UTC, sklirg commented on src/programs/group-manager.ts
> +  if (isNaN(deadtimeNumber)) {
What happens if the number is negative? What should happen?

2021-07-02 14:57 UTC, sklirg commented on src/programs/group-manager.ts
> +  });
This should handle the case of the group not being found.

2021-07-02 14:57 UTC, sklirg commented on src/programs/group-manager.ts
> +  await prisma.userGroup.update({
This should handle the case of the update failing.

2021-07-02 14:57 UTC, sklirg commented on src/programs/group-manager.ts
> +  return deadTime - Math.round(timeDifference);
The assignment of `deadTime` and `timeDifference` here can be confusing.

I'd suggest _not_ assigning `const deadTime = group.deadtime`, and rather use `return group.deadtime - ...`.

2021-07-02 14:57 UTC, sklirg commented on src/programs/group-manager.ts
> +      (Date.now() - lastMessages[1].createdTimestamp) / 1000 / 60;
This could return early instead of assigning and then returning after the conditional.

2021-07-02 14:57 UTC, sklirg commented on src/programs/group-manager.ts
> +  return deadTime - Math.round(timeDifference);
What should happen if the conditional fails? Currently, it returns the `group.deadtime` value that might always be above 0 (if the group has a deadtime configured).

2021-07-03 11:48 UTC, geisterfurz007 requested changes

2021-07-03 11:48 UTC, geisterfurz007 commented on src/programs/group-manager.ts
> +  }
There should be a return after this (otherwise the bot will add 👍 as well)

2021-07-03 11:56 UTC, hasanlatch007 commented on src/programs/group-manager.ts
> +  }
Bot is bipolar let it be :')

2021-07-03 12:30 UTC, geisterfurz007 approved these changes

2021-07-03 12:51 UTC, merged