Chore: replace hard coded IDs for Group Pings
Yes-Theory-Fam/yesbot-ts pull request #307
Opened 2021-06-24 19:59 UTC by hasanlatch007

for chore #302 
Hopefully, I got the idea correct

2021-06-24 20:50 UTC, adrian-goe commented
The idea is correct. But I would prefer an enum with the channel names, so all needed channels are in the same file.

2021-06-24 21:57 UTC, geisterfurz007 requested changes

2021-06-24 21:57 UTC, geisterfurz007 commented on src/programs/group-manager.ts
> +    ).id,
Instead of getting all channel IDs here, you can list the chat names here and change the return value of the function further down to `allowedChannels.includes(channel.name)`.

2021-06-25 09:21 UTC, geisterfurz007 approved these changes

2021-06-25 09:24 UTC, geisterfurz007 commented
Technically we can replace all the channel names in message.ts as well but since we want to tear the whole thing down anyway, I think it makes sense to use the enum when we move to the new event distribution 👍 
LGTM!

2021-06-25 09:24 UTC, merged