feat(*): send automatic release notes on start
Yes-Theory-Fam/yesbot-ts pull request #353
Opened 2021-07-03 22:47 UTC by adrian-goe

the bot can now find the commit-messages since the last deployment and
send them into the update channel

this is blocked by https://github.com/Yes-Theory-Fam/database/pull/18

2021-07-03 22:50 UTC, adrian-goe commented
This is how it would look like. The first one is a start with a new tag and the second one is for a reboot without any update
![Screenshot 2021-07-04 at 00 49 02](https://user-images.githubusercontent.com/17064122/124368473-a437f080-dc61-11eb-83a0-17160f8afd0b.png)

2021-07-04 11:44 UTC, geisterfurz007 requested changes

2021-07-04 11:44 UTC, geisterfurz007 commented on src/programs/release-notes.controller.ts
> +        updateChannel.send(message.tagMessage);
You can avoid the `@ts-ignore` by using `as TextChannel` after the find.

2021-07-04 11:44 UTC, geisterfurz007 commented on src/programs/release-notes.controller.ts
> +        botDevChannel.send(message.releaseNotes);
You can avoid the `@ts-ignore` by using `as TextChannel` after the find.

2021-07-04 11:44 UTC, geisterfurz007 commented on src/service/github-release-notes.service.ts
> +}
WebStorm reports this as unused.

2021-07-04 11:44 UTC, geisterfurz007 commented on src/service/github-release-notes.service.ts
> +  private async getCommitMessages(lastRelease: any, newRelease: Edge) {
```suggestion
  private async getCommitMessages(lastRelease: Release, newRelease: Edge) {
```

2021-07-04 11:44 UTC, geisterfurz007 commented on yarn.lock
> +  integrity sha512-UQWe9RwqrHBUoprs3RbmKaXAiqdrfDzwwk/X3chcJfpwSD5ATv3epn2UZa7YbJPjB0AmLtoGM2eZe1sdET1Tyg==
This will have to be regenerated, now that 0.9.0 is out.

2021-07-04 11:44 UTC, geisterfurz007 commented
I am a strong advocate for feature folders instead of having folders for each type of file (like service and accessor which were introduced in this PR). In development this means that you have to have three different directories open in the project explorer with potentially a dozen other files in there which have absolutely nothing to do with what you are working on, atm.

Instead, I think it would make sense to have `src/programs/release-notes/` (or `github-release-notes`) which would then contain all bits required for that feature to work (i.e. the types, API call to GitHub, service to handle the database and controller if we shall stick to the name for communication to Discord). That way if there was any work required on the feature, I have one folder I need to open and have everything needed to work on it.

This setup would also mean that a bunch of extra .ts / .js files are loaded by the event distribution. We could mitigate that by using a more specific file extension like .controller.ts which you already started using here to make sure only relevant files are picked up by the glob pattern (although I am not sure loading a couple more files on startup will have that much impact on startup time at the small scale of YesBot).

2021-07-04 11:56 UTC, adrian-goe commented
I kinda agree with you but on the other side not. The reason is a Clean Architecture approach where you have layers.
If all the files related to one feature set in one directory would mean a strong coupling with potential a lot of rewritten code.
By using a folder for a layer, we can reuse the GitHub accessor for other things.
In the layers, I agree we can sort this in directories, so it isn't that overwhelming.

2021-07-05 17:40 UTC, geisterfurz007 reviewed
Rest LGTM for now; pipeline still disagrees though

2021-07-05 17:40 UTC, geisterfurz007 commented on __tests__/programs/release-notes/usecase/github-release-notes.usecase.spec.ts
> +  it("should sort CommitMessages", () => {
Should sort releases?

2021-07-17 11:49 UTC, geisterfurz007 approved these changes
LGTM!

2021-07-17 11:49 UTC, merged