fixed yestheoryuploaded ping
Yes-Theory-Fam/yesbot-ts pull request #361
Opened 2021-07-11 20:24 UTC by hasanlatch007

If webhooks count as bots this should not return an error and we should no longer need to use `hasRole`.
Used the test YesBot by forcing it to send a message in #yestheory-uploaded which pinged the group.

2021-07-11 20:27 UTC, hasanlatch007 commented
This actually might not work I checked the discord.js docs and webhooks are not logged in as bots? So `message.author.bot` might always return false, I'm not sure of this I gotta read the docs a bit better.
`if (message.webhookID)` Will have to replace it with this I think :')

2021-07-11 21:24 UTC, hasanlatch007 commented
Both `webhookID` or `message.author.bot` work but the first one will only return true if the message is from a webhook that serves our goal better.

2021-07-12 18:04 UTC, geisterfurz007 requested changes

2021-07-12 18:04 UTC, geisterfurz007 commented on src/programs/yestheory-content.ts
> +  if (message.webhookID) {
Use an early return instead.

2021-07-12 18:04 UTC, geisterfurz007 commented
`webhookID` was a really nice catch!

2021-07-12 18:11 UTC, hasanlatch007 commented on src/programs/yestheory-content.ts
> +  if (message.webhookID) {
Done :)

2021-07-12 18:11 UTC, hasanlatch007 commented
> `webhookID` was a really nice catch!

I used my big brain for once :D

2021-07-12 18:12 UTC, geisterfurz007 approved these changes

2021-07-12 18:12 UTC, merged