Feat: Option for group ping
Yes-Theory-Fam/yesbot-ts pull request #362
Opened 2021-07-15 21:59 UTC by hasanlatch007

Welp, I got bored, and decided to work on this, probably needs lots of feedback, legit coded this in 30 minutes, works as intended but I feel like I could improve it better.

2021-07-23 22:15 UTC, geisterfurz007 requested changes

2021-07-23 22:15 UTC, geisterfurz007 commented on src/programs/group-manager.ts
> +        ``,
Empty string should be removed.

2021-07-23 22:15 UTC, geisterfurz007 commented on src/programs/group-manager.ts
> +      data: { groupPingOption: setting },
`groupPingOption` does not exist in the current database schema.

Available options should also be [defined as enum](https://www.prisma.io/docs/concepts/components/prisma-schema/data-model#defining-enums). I believe that will also generate them as TS so the string comparisons further above should be replaced with those enums.

2021-07-24 12:13 UTC, hasanlatch007 commented on src/programs/group-manager.ts
> +        ``,
This was resolved my bad!

2021-07-24 12:13 UTC, hasanlatch007 commented on src/programs/group-manager.ts
> +      data: { groupPingOption: setting },
I created a PR on the database github, all options have been defined as enum

2021-07-26 10:13 UTC, hasanlatch007 commented
If this is good to go dont merge it till i delete the function michel added for the group YesTheoryUploaded

2021-07-30 14:26 UTC, geisterfurz007 commented on src/programs/group-manager.ts
> +    !setting
- This should use the enum values as well
-  `|| !setting` is redundant because an empty string or undefined won't match any of the previous cases either.

2021-07-31 13:11 UTC, geisterfurz007 requested changes
- Update @yes-theory-fam/database to 0.11.0
- Remove this: https://github.com/Yes-Theory-Fam/yesbot-ts/blob/dafd7cb319bb834d37bacc658aa32b9c4456b928/src/programs/group-manager.ts#L916-L919

2021-07-31 13:45 UTC, geisterfurz007 approved these changes

2021-07-31 13:45 UTC, merged