Feat: Auto-detect timeout evasion
Yes-Theory-Fam/yesbot-ts pull request #374
Opened 2021-07-21 23:48 UTC by hasanlatch007

This should close #370

2021-07-21 23:50 UTC, hasanlatch007 commented
Testing failed because `timedOutUsers` does not exists in the db yet.

2021-07-22 09:16 UTC, geisterfurz007 requested changes
We shouldn't inline so much code into events and other programs, especially given the new event system which tries to shift focus onto more capsulated features.

Instead of putting some bits into moderator.ts, guild-member-update.ts, member-leave.ts, message.ts *and* where-are-you-from.ts, you should use the new event system for creating event handlers in a dedicated directory under src/programs.

2021-07-22 13:10 UTC, hasanlatch007 commented
Aha then i would need to understand the new event system will ask Adrian for some help :)

2021-08-08 22:54 UTC, hasanlatch007 commented
Blocked until #403 is merged, DB is bumped with support for user data table, and Winston loggers are added

2021-08-08 23:18 UTC, hasanlatch007 commented
I moved the `lostRole` and `gainedRole` from `moderation.ts` to `tools.ts` since I feel like it's more suitable there?

2021-08-09 19:11 UTC, geisterfurz007 requested changes

2021-08-09 19:11 UTC, geisterfurz007 commented on src/common/moderator.ts
> +};
This is specific to the timeout evasion functionality so it should be moved to that file.

2021-08-09 19:11 UTC, geisterfurz007 commented on src/programs/timeout-evasion.ts
> +    if (await Tools.lostRole(oldMember, newMember, "Time Out")) {
You can split this a little bit further by creating two classes; one handling the role being added and one handling the role being removed. The options for GUILD_MEMBER_UPDATE take `roleNamesAdded` and `roleNamesRemoved`, so one handler would be

```ts
@Command({
  event: DiscordEvent.GUILD_MEMBER_UPDATE,
  roleNamesAdded: ["Time Out"],
})
```
and the other one the same with `roleNamesRemoved` instead of `roleNamesAdded` (feel free to add descriptions as desired).

That also removes the need for the checks whether the member has gained or lost a role since that is guaranteed to have happened based on the options given.

2021-08-09 19:11 UTC, geisterfurz007 commented on src/programs/timeout-evasion.ts
> +      }
In such a case, also log the error. Otherwise while a developer may have been contacted, they have absolutely no idea what happened since there is no trace of this event anywhere in the logs.

2021-08-09 19:11 UTC, geisterfurz007 commented on src/programs/timeout-evasion.ts
> +        );
See comment above.

2021-08-09 19:11 UTC, geisterfurz007 commented on src/programs/timeout-evasion.ts
> +    const timeoutRole = Tools.getRoleByName("Time Out", guild);
```suggestion
    const timeoutRole = Tools.getRoleByName("Time Out", member.guild);
```

2021-08-09 19:13 UTC, hasanlatch007 commented on src/programs/timeout-evasion.ts
> +      }
I did say, ill be adding the logger at the end, just right now it's the functionality I'm aiming for.

2021-08-09 19:14 UTC, geisterfurz007 commented on src/programs/timeout-evasion.ts
> +      }
Ooooooooooh derp; I misread that comment, sorry!

2021-08-09 19:29 UTC, hasanlatch007 commented on src/programs/timeout-evasion.ts
> +      }
It's okay we all misread comments sometimes :p

2021-08-09 20:00 UTC, hasanlatch007 commented
Did some final cleanup, moved all functions necessary, and added the logger, all that is left is the DB, Adrian said he's working on that but since he is busy maybe I can do it? Or at least the part we need.

2021-08-11 18:20 UTC, geisterfurz007 commented
Database has been bumped to 0.13.0 on master; if you rebase and run yarn, the table should exist. I removed the blocked label.

2021-08-11 20:16 UTC, geisterfurz007 commented
To have working code on this branch, please rebase this branch:

```
git fetch
git rebase origin/master
# Fix potential merge conflicts and git rebase --continue after fixing them, keep going until the rebase was successful
git push --force-with-lease
```

2021-08-11 20:55 UTC, hasanlatch007 commented
Should be good to go!

2021-08-12 17:27 UTC, geisterfurz007 requested changes

2021-08-12 17:27 UTC, geisterfurz007 commented on src/programs/timeout-evasion.ts
> +    );
You can move this to the catch clause to avoid iterating through the roles in case there was no error.

2021-08-12 17:27 UTC, geisterfurz007 commented on src/programs/timeout-evasion.ts
> +      logger.error("Failed to add user to the DB " + e);
If `e` is an object, this will end up as `"Failed to add user to the DB [object object]"`. You can pass the error as second argument to have it properly show in the log output:

```suggestion
      logger.error("Failed to add user to the DB ", e);
```

2021-08-12 17:27 UTC, geisterfurz007 commented on src/programs/timeout-evasion.ts
> +    );
See comment above.

2021-08-12 17:27 UTC, geisterfurz007 commented on src/programs/timeout-evasion.ts
> +      logger.error("Failed to remove user from the DB " + e);
See comment above.

2021-08-13 16:53 UTC, geisterfurz007 approved these changes

2021-08-13 16:53 UTC, merged