Fix/detect multiple flags
Yes-Theory-Fam/yesbot-ts pull request #395
Opened 2021-08-06 16:01 UTC by hasanlatch007

This should close #382, the way emojis are on discord is combining multiple emojis together (does this even make sense..?). The current regex splits them up separately, combines the first 2 indexes and the last 2 in the array, which together will give the first 2 flags send. If they are different, the bot replies with the message. This kind of can be bypassed by sending the same flag twice then a different one but either way he will still get assigned the role of the first flag detected, but the bug was mostly having the same flag twice and it gets detected as different, so that doesn't really matter.

2021-08-14 09:04 UTC, geisterfurz007 requested changes

2021-08-14 09:04 UTC, geisterfurz007 commented on src/programs/where-are-you-from.ts
> +
The fix for detecting multiple countries should be moved to `CountryRoleFinder#getCountriesFromString` to make it only return the countries that are there.

Then we can have the tests in `__tests__/utils/country-role-finder.spec.ts` to verify everything works as expected (there is already one case commented out that relates to this issue).

2021-08-14 09:04 UTC, geisterfurz007 commented on src/programs/where-are-you-from.ts
> +      seperatedEmojis[2] + seperatedEmojis[3] &&
This allows 🇮🇳🇮🇳🇩🇪 to go through.

2021-08-14 11:23 UTC, hasanlatch007 commented on src/programs/where-are-you-from.ts
> +      seperatedEmojis[2] + seperatedEmojis[3] &&
I already said that this fix only detects for the first 2 flags, if they are the same everything is good to go, I didn't want to use a `for` to not have it use too many resources in case someone decided to spam flags, maybe I can limit the for to only check for the first 6 flags?

2021-08-14 11:28 UTC, geisterfurz007 commented on src/programs/where-are-you-from.ts
> +      seperatedEmojis[2] + seperatedEmojis[3] &&
Oh, whoops, sorry about that!

I think it's fairly safe to use a loop; I have yet to see someone spam flags in a single message. Those with ill intent are more likely to spam large blocks of text or malicious links.

2021-08-14 16:40 UTC, hasanlatch007 commented
This is still broken, but any ideas are always welcomed!

2021-08-18 18:04 UTC, geisterfurz007 approved these changes

2021-08-18 18:07 UTC, merged