Feat: timeout with timer support
Yes-Theory-Fam/yesbot-ts pull request #399
Opened 2021-08-07 14:46 UTC by hasanlatch007

Im still pretty new at the event system, so if you got any comments don't be afraid to be harsh :)

2021-08-07 15:06 UTC, geisterfurz007 requested changes
Didn't try it out yet but the use of the events looks good!

2021-08-07 15:06 UTC, geisterfurz007 commented on src/programs/timeout-timer.ts
> +    }
I think we can shorten that by dropping the last two cases and using || instead of && in the first if.

2021-08-07 15:06 UTC, geisterfurz007 commented on src/programs/timeout-timer.ts
> +    const channel = bot.channels.resolve(data.channelId) as TextChannel;
This channel is only used to access the guild. You can use `const guild = bot.guilds.resolve(process.env.GUILD_ID)` instead. That also means that you can drop the channelId from TimeoutTimerData.

2021-08-07 15:06 UTC, geisterfurz007 commented on src/programs/timeout-timer.ts
> +    const memberGuild = channel.guild.members.resolve(data.userId);
I think the name `guildMember` fits better. The returned value is not a guild but a member. `GuildMember` is also the classname in Discord.js.

2021-08-08 15:50 UTC, geisterfurz007 requested changes
Rest looks and works fantastically!

2021-08-08 15:50 UTC, geisterfurz007 commented on src/programs/timeout-timer.ts
> +    ) as TextChannel;
Missed that in my last review; you can use `textLog` from `src/common/moderator.ts` to log to bot-output instead of looking up the channel here, so this could be removed (and the two `logChannel.send` calls replaced with textLog).

2021-08-08 16:13 UTC, hasanlatch007 commented on src/programs/timeout-timer.ts
> +    ) as TextChannel;
Also changed it in `timeout.ts`

2021-08-09 18:29 UTC, geisterfurz007 requested changes
Last one, I promise!

2021-08-09 18:29 UTC, geisterfurz007 commented on src/programs/timeout-timer.ts
> +    );
```suggestion
    const timeoutRole = Tools.getRoleByName("Time Out", message.guild);
```

2021-08-09 18:29 UTC, geisterfurz007 commented on src/programs/timeout-timer.ts
> +    const timeoutRole = guild.roles.cache.find((r) => r.name === "Time Out");
```suggestion
    const timeoutRole = Tools.getRoleByName("Time Out", guild);
```

2021-08-11 18:11 UTC, geisterfurz007 approved these changes

2021-08-11 18:11 UTC, merged