feat: hide all other channels when joining a productivity channel
Yes-Theory-Fam/yesbot-ts pull request #406
Opened 2021-08-13 18:08 UTC by hasanlatch007

A quick reminder of fixing the voice channels permissions so users on the Break role can still see the productivity channels!
This closes #198

2021-08-14 09:14 UTC, geisterfurz007 requested changes
This is also missing the logic for adding exceptions for the prod voice channels and voice-chat-wip.

2021-08-14 09:14 UTC, geisterfurz007 commented on src/programs/productivity-toggle.ts
> +class addBreakRoleOnJoin
```suggestion
class AddBreakRoleOnJoin
```

2021-08-14 09:14 UTC, geisterfurz007 commented on src/programs/productivity-toggle.ts
> +      const BreakRole = Tools.getRoleByName("Break", newState.guild);
```suggestion
      const breakRole = Tools.getRoleByName("Break", newState.guild);
```

2021-08-14 09:14 UTC, geisterfurz007 commented on src/programs/productivity-toggle.ts
> +      const BreakRole = Tools.getRoleByName("Break", oldState.guild);
```suggestion
      const breakRole = Tools.getRoleByName("Break", oldState.guild);
```

2021-09-04 23:00 UTC, geisterfurz007 requested changes

2021-09-04 23:00 UTC, geisterfurz007 commented on src/programs/productivity-toggle.ts
> +        channel.name != ChatNames.WATCH_ME_WORK_TOO)
For better readability and maintainability (throughout the entire file), it's probably a good idea to create a function like this:

```ts
const isProdVoiceChannel = (channel: VoiceChannel) => {
  const prodVCNames = [ChatNames.PRODUCTIVITY, ChatNames.WATCH_ME_WORK, ChatNames.WATCH_ME_WORK_TOO];
  return prodVCNames.includes(channel.name);
};
```

2021-09-04 23:04 UTC, hasanlatch007 commented on src/programs/productivity-toggle.ts
> +    "This handler checks if the user left one of the productivity channels",
LMAO, I have no clue why that is there :')

2021-09-05 17:59 UTC, geisterfurz007 requested changes

2021-09-05 17:59 UTC, geisterfurz007 commented on src/programs/productivity-toggle.ts
> +    const ProductivityChannels = channel.guild.channels.cache.find(
Variables start with a lowercase letter; `find` returns a single object so no plural 's' -> `const productivityChannel`.

2021-09-05 17:59 UTC, geisterfurz007 commented on src/programs/productivity-toggle.ts
> +    const ProductivityChannel = channel.guild.channels.cache.find(
See above.

2021-09-05 17:59 UTC, geisterfurz007 commented on src/programs/productivity-toggle.ts
> +    }
Untested but can you use something like this by any chance?

```ts
  const commonPermissions = {
    VIEW_CHANNEL: true,
    CONNECT: true,
    STREAM: true,
    USE_VAD: true,

    SEND_MESSAGES: true,
    READ_MESSAGE_HISTORY: true,
  };

  for (const chatName of prodVoiceChats) {
    const productivityChannel = channel.guild.channels.cache.find(
      (c) => c.name === chatName
    );

    await productivityChannel.updateOverwrite(member.id, {
      ...commonPermissions,
      SPEAK: chatName !== ChatNames.PRODUCTIVITY,
    });
  }
};
```
I cannot recall whether the API murders you if you provide text permissions for a voice channel and vice versa. If it doesn't, this would be a neat and clean way to solve this.

2021-09-05 17:59 UTC, geisterfurz007 commented on src/programs/productivity-toggle.ts
> +  if (channel === null) return;
```suggestion
  if (channel === null) return false;
```

2021-09-05 17:59 UTC, geisterfurz007 commented on src/programs/productivity-toggle.ts
> +      return;
At this point it's probably easier to turn it around ;)

The idea behind early returns is to save indentation and reduce the level of nesting for the code that follows, especially if that nested code is long in an effort to increase readability.

Instead of reading "if switch from prod to prod, return", "if switch from non prod to prod, return", "if switch between non-prod channels, return", leaving you with "if switch from prod to non prod, do stuff", just reading that last part saves a lot of the thinking and with only two lines that will end up running under that condition, it's reasonable to go for "normal" nesting here :)

2021-10-01 05:50 UTC, adrian-goe requested changes

2021-10-01 05:50 UTC, adrian-goe commented on src/programs/productivity-toggle.ts
> +class AddBreakRoleOnJoin
Please move each command into its own class. Create a folder for this sub-project. you can look into [release-notes](https://github.com/Yes-Theory-Fam/yesbot-ts/tree/master/src/programs/release-notes) or [activity](https://github.com/Yes-Theory-Fam/yesbot-ts/tree/master/src/programs/activity) to see what i mean

2021-10-01 05:50 UTC, adrian-goe commented on src/programs/productivity-toggle.ts
> +@Command({
Please move each command into its own class. Create a folder for this sub-project. you can look into [release-notes](https://github.com/Yes-Theory-Fam/yesbot-ts/tree/master/src/programs/release-notes) or [activity](https://github.com/Yes-Theory-Fam/yesbot-ts/tree/master/src/programs/activity) to see what i mean

2021-10-01 05:50 UTC, adrian-goe commented on src/programs/productivity-toggle.ts
> +class RemoveBreakRoleOnLeave
Please move each command into its own class. Create a folder for this sub-project. you can look into [release-notes](https://github.com/Yes-Theory-Fam/yesbot-ts/tree/master/src/programs/release-notes) or [activity](https://github.com/Yes-Theory-Fam/yesbot-ts/tree/master/src/programs/activity) to see what i mean

2021-10-01 05:50 UTC, adrian-goe commented on src/programs/productivity-toggle.ts
> +@Command({
Please move each command into its own class. Create a folder for this sub-project. you can look into [release-notes](https://github.com/Yes-Theory-Fam/yesbot-ts/tree/master/src/programs/release-notes) or [activity](https://github.com/Yes-Theory-Fam/yesbot-ts/tree/master/src/programs/activity) to see what i mean

2021-10-01 05:50 UTC, adrian-goe commented on src/programs/productivity-toggle.ts
> +@Command({
Please move each command into its own class. Create a folder for this sub-project. you can look into [release-notes](https://github.com/Yes-Theory-Fam/yesbot-ts/tree/master/src/programs/release-notes) or [activity](https://github.com/Yes-Theory-Fam/yesbot-ts/tree/master/src/programs/activity) to see what i mean

2021-10-01 05:50 UTC, adrian-goe commented on src/programs/productivity-toggle.ts
> +};
The same applies to the functions. This then ensures that we have small readable files.

2021-10-01 05:50 UTC, adrian-goe commented on src/programs/productivity-toggle.ts
> +};
The same applies to the functions. This then ensures that we have small readable files.

2021-10-01 05:50 UTC, adrian-goe commented on src/programs/productivity-toggle.ts
> +};
The same applies to the functions. This then ensures that we have small readable files.

2022-10-07 07:38 UTC, hasanlatch007 commented
Closing this since it is too old, and will need to be updated, better start from scratch.

2022-10-07 07:38 UTC, closed without merging

2022-10-07 17:44 UTC, geisterfurz007 commented
It's unsure whether this should actually be reimplemented; there has been a split between the regulars in the prod channels and forcing something onto people while the other could just fix their own discipline might not be a good idea.