Chore: Refactored nitro-colors
Yes-Theory-Fam/yesbot-ts pull request #442
Opened 2021-08-21 17:21 UTC by hasanlatch007

!closes #439

2021-08-22 14:05 UTC, geisterfurz007 requested changes

2021-08-22 14:05 UTC, geisterfurz007 commented on src/events/reaction-add.ts
> +    await guildMember.roles.add(roleToAdd);
Having this around breaks things. The reactions don't honor the exception for nitro anymore so what happens now is that the role is added, then the handler is called and detects that the user already has a nitro role (which was added here) and removes the reaction again.

With this left over, we also allow having multiple color roles. I am not entirely sure how that works because removing the reaction should also remove the role but that doesn't appear to happen in this case.

2021-08-22 17:50 UTC, hasanlatch007 commented on src/events/reaction-add.ts
> +    await guildMember.roles.add(roleToAdd);
Not really sure why the role was not being removed but figured it was mostly both events colliding with each other I'm mostly assuming that the old event was quicker and added the role immediately while the event in `nitro-colors.ts` was still running it sees that they already have a role and only removes their reaction and not the role. Anyways since I don't feel like deleting half of `reaction-add.ts` YET, decided to add a simple `if` and let the event in `nitro-colors.ts` handle adding the roles or removing them.

2021-08-24 11:40 UTC, geisterfurz007 requested changes

2021-08-24 11:40 UTC, geisterfurz007 commented on src/events/reaction-add.ts
> +  if (isColorSelectionMessage(messageId) && memberHasNitroColor(guildMember))
This still suffered from some weird race-condition. This should fix it though (we don't want this file to handle nitro colors, no matter whether the member already has a nitro color or not):
```suggestion
  if (isColorSelectionMessage(messageId))
```

2021-08-24 12:18 UTC, geisterfurz007 approved these changes

2021-08-24 12:18 UTC, merged