Chore: Refactored daily-challenge
Yes-Theory-Fam/yesbot-ts pull request #446
Opened 2021-08-21 22:40 UTC by hasanlatch007

The `READY` event would be used as a kickstart and never used again unless the bot was stopped when `PostDailyChallenge` was being executed and stopped before it could run the `scheduleTimer`, then it will be used again
Also in case, this fails added a command to be able to reset it.
This !closes #425

2021-08-21 23:09 UTC, hasanlatch007 commented
Just realized i forgot to set the time correctly wait for the new commit before reviewing

2021-08-22 14:23 UTC, geisterfurz007 requested changes

2021-08-22 14:23 UTC, geisterfurz007 commented on src/programs/daily-challenge.ts
> +      });
This code fragment has been duplicated twice in this file; stay [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself).

2021-08-24 12:02 UTC, geisterfurz007 requested changes

2021-08-24 12:02 UTC, geisterfurz007 commented on src/programs/daily-challenge.ts
> +        });
Dupe

2021-08-24 12:02 UTC, geisterfurz007 commented on src/programs/daily-challenge.ts
> +      );
No worries about that; it would blow up in line 157 before getting here :)

2021-08-24 14:53 UTC, hasanlatch007 commented
blocked until https://github.com/Yes-Theory-Fam/database/pull/40 is merged

2021-08-24 17:09 UTC, geisterfurz007 commented
Merged *and* published! Upgrade database to 0.14.0 for the fix

2021-09-03 17:39 UTC, geisterfurz007 requested changes

2021-09-03 17:39 UTC, geisterfurz007 commented on src/programs/daily-challenge.ts
> +  executeTime.setMinutes(executeTime.getDate() + executionDate);
```suggestion
  executeTime.setDate(executeTime.getDate() + executionDate);
```

2021-09-03 19:45 UTC, geisterfurz007 approved these changes
:shipit:

2021-09-03 19:45 UTC, merged