Chore: Refactor !voice
Yes-Theory-Fam/yesbot-ts pull request #465
Opened 2021-08-29 21:14 UTC by hasanlatch007

This still needs testing but I wanted to leave this PR here to show the progress so far.
Early reviews are always welcomed (Michel 👀)
!closes #433

2021-08-30 18:50 UTC, hasanlatch007 commented
My internet kept crashing during testing, which made me lost track of what I tested. I heavily tested the implemented `TIMER EVENT` to be able to delete the channel or requestNewHost and it works like a charm!

2021-08-30 19:41 UTC, hasanlatch007 commented
This is not the cleanest approach for splitting up the functions, but it is better than exporting a bunch of constants from `tools.ts` for variables like `maxLimit` and the identifiers

2021-09-03 18:10 UTC, geisterfurz007 requested changes

2021-09-04 12:14 UTC, geisterfurz007 requested changes
The bot is currently missing an implementation to check all channels on startup as is currently done:

https://github.com/Yes-Theory-Fam/yesbot-ts/blob/88e5be34f05abf01e5fdac1cbc83f7e163dd3c60/src/programs/voice-on-demand.ts#L439-L444

2021-09-04 12:14 UTC, geisterfurz007 commented on src/programs/voice/voice-timer.ts
> +    if (!oldState.channel || oldState.channelID === newState.channelID) return;
`oldState.channel` should never be falsy so the first part of the condition can be removed.

2021-09-04 12:14 UTC, geisterfurz007 commented on src/programs/voice/voice-timer.ts
> +  implements CommandHandler<DiscordEvent.VOICE_STATE_UPDATE>
This is not timer related and not a good fit for this file; maybe voice-create is more suitable since it's somewhat tied to that?

2021-09-04 12:14 UTC, geisterfurz007 commented on src/programs/voice/voice-create.ts
> +const voiceOnDemandDeleteIdentifier = "voiceondemandchanneldelete";
This is duplicated from voice-timer.ts; it's probably best to export the identifier from there and use it here to avoid things breaking if the identifier ever changes and is only changed in one place.

2021-09-04 12:14 UTC, geisterfurz007 commented on src/programs/voice/voice-timer.ts
> +    });
Is it? The check shouldn't be done every minute; it should be triggered by the last person leaving.

2021-09-04 12:17 UTC, geisterfurz007 commented on src/programs/voice/voice-timer.ts
> +    });
Some further reasoning: This could introduce flawed behaviour. Imagine the timer triggers every full minute. Last member leaves at 13:00:58; the channel closes 2 seconds after the last person left instead of a minute. Thus checking periodically is not ideal.

2021-09-04 12:19 UTC, hasanlatch007 commented on src/programs/voice/common.ts
> +    requestedLimit: any,
It would break the `Number()` function when setting it as a string

2021-09-04 14:46 UTC, geisterfurz007 commented on src/programs/voice/common.ts
> +    requestedLimit: any,
In TypeScript, declaring a parameter as `any` tells the compiler to just shut up which is the reason it should be avoided. The errors you get when declaring requestedLimit as string are correct, because you are not supposed to pass a string into Math.floor or Math.min.

Here is what I would propose:

```ts
  static async handleLimitCommand(
    message: Message,
    requestedLimitString: string, // Renamed this variable and changed type
    createCommand?: boolean
  ): Promise<number> {
    const requestedLimit = Number(requestedLimitString); // Added this line

    if (!requestedLimit && createCommand) return defaultLimit;
    
    /* Rest of the function */
```

2021-09-04 22:07 UTC, geisterfurz007 reviewed
Sadly the timers break one thing and quite subtly at that.

1) Create channel
2) Connect after 30 seconds
3) Disconnect after 5 seconds

-> Expectation: Channel is deleted 1 minute after disconnecting
-> Actual: Channel is deleted 25 seconds after disconnecting because the previous timer is not cancelled

I am afraid this might end up blocked for a bit while I add stuff to cancel timers to the timer-service.

2021-11-19 17:27 UTC, geisterfurz007 commented
Scrolling through open PRs, I found this is not blocked anymore, now that timer cancels are a thing.

2021-11-19 17:30 UTC, hasanlatch007 commented
> Scrolling through open PRs, I found this is not blocked anymore, now that timer cancels are a thing.

Yes I know, but I left it mostly blocked until my laptop comes back from repairs `voice` requires lots of testing before even submitting new code for it, with this slow mac that is near impossible :'), I'll start working on them once I have the chance.

2022-06-12 19:32 UTC, hasanlatch007 commented
I'll rework this on a new PR since this one is too old.

2022-06-12 19:32 UTC, closed without merging