refactored map.ts
Yes-Theory-Fam/yesbot-ts pull request #481
Opened 2021-09-09 20:40 UTC by AdamWarden

!closes #427

2021-09-09 20:48 UTC, hasanlatch007 commented on src/programs/map.ts
> +      await message.reply(
You no longer need to have `map` as a function.
In TS when you use the `=>` or called "Fat arrow" is a way to write a concise function, with the new event handlers this technique is no longer since the class object is now our function, plus `async handle()` is our actual function thus you can delete that line.

2021-09-09 20:48 UTC, hasanlatch007 commented on src/programs/map.ts
> +      split.shift();
See comment above

2021-09-09 20:51 UTC, hasanlatch007 commented on src/programs/map.ts
> +})
This is currently only one command which is triggered by the trigger set "!map", which is different from "!mapadd" so you're going to have to split them up.
Also, the description is preferably to explain the command and not the code.

2021-09-09 21:03 UTC, hasanlatch007 requested changes
There are also leftovers from map.ts that you're going to have to delete in these files
https://github.com/Yes-Theory-Fam/yesbot-ts/blob/master/src/events/message.ts
https://github.com/Yes-Theory-Fam/yesbot-ts/blob/master/src/programs/index.ts

2021-09-11 21:43 UTC, hasanlatch007 commented on src/programs/map.ts
> +  description: "command to view the yf map",
```suggestion
  description: "This handler is to show the Yes Theory Fam map",
```

2021-09-11 21:44 UTC, hasanlatch007 commented on src/programs/map.ts
> +  description: "adds location of user to yf map",
```suggestion
  description: "This handler is to request to add your location to the Yes Theory Fam map",
```

2021-09-11 21:54 UTC, hasanlatch007 requested changes

2021-09-11 21:54 UTC, hasanlatch007 commented on src/programs/map.ts
> +}
This is an unreachable code, you added the code after the return. You have to take out the code after your return and put it outside the if brackets
```suggestion
    if (!city) {
      await Tools.handleUserError(
        message,
        "You need to add the city you are from!"
      );
      return;
      }
      //rest of code here
```

2021-09-11 21:54 UTC, hasanlatch007 commented on src/programs/map.ts
> +@Command({
You have to put the code that is related to `!mapadd` to this just imagine 2 separate commands with their own code. You can't stack them like this.

2021-09-11 21:54 UTC, hasanlatch007 commented on src/programs/map.ts
> +      UserID: ${message.author.id}
```suggestion
      UserID: ${author.id}
```

2022-02-05 10:26 UTC, geisterfurz007 commented
This hasn't seen activity in several months; closing. Feel free to let me know if you pick this up again!

2022-02-05 10:26 UTC, closed without merging