Chore: Removed old events for reactions and refactored !group Toggle
Yes-Theory-Fam/yesbot-ts pull request #500
Opened 2021-09-22 22:51 UTC by hasanlatch007

Since `role-react` and `!group-toggle` are being refactored any events related to reactions in the old event folder can be deleted
This still needs testing and reformatting :)

!closes #498

2021-09-22 22:52 UTC, hasanlatch007 commented
Github why are you being shit?

2021-09-23 02:49 UTC, hasanlatch007 commented
This PR adds multiple fixes for `reactionRole`, where when adding the reaction the bot would also get the role.

2021-09-29 17:31 UTC, geisterfurz007 requested changes

2021-09-29 17:31 UTC, geisterfurz007 commented on src/programs/channel-toggle/channel-toggle-add.ts
> +const logger = createYesBotLogger("program,", "channelToggleRemove");
```suggestion
const logger = createYesBotLogger("program", "channelToggleRemove");
```
;)

2021-09-29 17:31 UTC, geisterfurz007 commented
Rest LGTM, nice work!

2021-09-29 18:51 UTC, geisterfurz007 approved these changes

2021-09-29 18:54 UTC, merged