Chore: Refactored game.ts and fix reaction
Yes-Theory-Fam/yesbot-ts pull request #510
Opened 2021-09-27 21:10 UTC by hasanlatch007

I refactored what I felt was necessary for anything related to the old event handler. Not touching the hubs or other like just commands.
This will have a merge conflict with the PR #500 as the old reaction event handler had an issue picking up reaction added in DMs,
This should be fixed in this PR and also fixed in #500 as that file will be deleted

!closes #478

2021-10-05 20:23 UTC, adrian-goe requested changes

2021-10-05 20:23 UTC, adrian-goe commented on src/programs/game.ts
> +}
move into own file

2021-10-05 20:23 UTC, adrian-goe commented on src/programs/game.ts
> +}
move into own file

2021-10-05 20:23 UTC, adrian-goe commented on src/programs/game.ts
> +}
move into own file

2021-11-25 20:10 UTC, hasanlatch007 commented
Games have been removed from the bot. This PR can be closed

2021-11-25 20:10 UTC, closed without merging