Chore: refactored group.ts
Yes-Theory-Fam/yesbot-ts pull request #512
Opened 2021-09-29 23:29 UTC by hasanlatch007

!closes #426

2021-10-05 20:25 UTC, adrian-goe requested changes
This code is only copied and pasted. Please move the logical part into service classes and split them up into smaller function. Otherwise, it's not really a refactoring

2021-11-19 17:35 UTC, geisterfurz007 requested changes

2021-11-19 17:35 UTC, geisterfurz007 commented on src/programs/group-manager/admin-commands/group-changeCooldown.ts
> +        return;
Switching to then/catch calls means the early return serves no purpose; it also means that the 👍 will still be added. What was the reason for using callbacks instead of try/catch?

This change including the unwanted side-effects occured several times; I will just put a sloth there so you know it refers to this as well 🦥.

2021-11-19 17:35 UTC, geisterfurz007 commented on src/programs/group-manager/admin-commands/group-changePingSettings.ts
> +        return;
🦥

2021-11-19 17:35 UTC, geisterfurz007 commented on src/programs/group-manager/admin-commands/group-create.ts
> +        return;
🦥

2021-11-19 17:35 UTC, geisterfurz007 commented on src/programs/group-manager/admin-commands/group-deadtime.ts
> +        return;
🦥

2021-11-19 17:35 UTC, geisterfurz007 commented on src/programs/group-manager/admin-commands/group-delete.ts
> +      });
🦥

2021-11-19 17:35 UTC, geisterfurz007 commented on src/programs/group-manager/admin-commands/group-update.ts
> +        return;
🦥

2022-02-20 11:53 UTC, geisterfurz007 requested changes

2022-02-20 11:53 UTC, geisterfurz007 commented on src/programs/group-manager/user-commands/group-ping.ts
> +    ChatNames.YESTHEORY_DISCUSSION.toString(),
toString calls aren't needed

2022-02-20 11:53 UTC, geisterfurz007 commented on src/programs/group-manager/user-commands/group-ping.ts
> +  trigger: "@group",
This introduces a regression:

```
Some text
@group test
```
pings the group on the server at the moment but won't anymore with this code. Since this is something actively done (prime example is the DailyMonkey group), this should be fixed.

2022-02-20 11:53 UTC, geisterfurz007 commented on src/programs/group-manager/user-commands/group-join.ts
> +  channelNames: ["bot-commands", "permanent-testing"],
Use names from `ChatNames` enum (goes for other handlers as well).

2022-02-20 19:49 UTC, geisterfurz007 approved these changes
LGTM!

2022-02-20 19:50 UTC, merged