Feat: Expand menu.ts and let bot handle break role
Yes-Theory-Fam/yesbot-ts pull request #582
Opened 2021-11-04 21:45 UTC by hasanlatch007

I split the commands a bit so when @adrian-goe adds the coin feature he would be easily able to implement it.
Currently, this only sets the preparation for the new feature of letting the bot handle the `break` role
Also added it to its own personal folder for future usage for Adrian's features :)

!closes #196

2021-11-23 07:06 UTC, adrian-goe commented
That's 2 seperate things in one MR.
Also, you need to rebase.

2021-11-26 22:12 UTC, hasanlatch007 commented
This requires https://github.com/Yes-Theory-Fam/database/pull/95 to be merged.

2021-11-27 17:56 UTC, geisterfurz007 requested changes
database@0.19.0 is available now as well

2021-11-27 17:56 UTC, geisterfurz007 commented on src/programs/menu/break-handler/addBreak.ts
> +import prisma from "../../../prisma";
File name should be in line with our naming convention -> `add-break.ts`.

2021-11-27 17:56 UTC, geisterfurz007 commented on src/programs/menu/break-handler/addBreak.ts
> +    "It looks like you want a little break! It is understandable you can get it by clicking on the :sloth: emoji below. You can send me !menu again to remove it.\n**BE ADVISED: THIS COMMAND CAN ONLY
```suggestion
    "It looks like you want a little break! It is understandable you can get it by clicking on the :sloth: emoji below. You can send me !menu again to remove it.\n**Be advised: You can only toggle your break role every 24 hours**"
```
No need to yell at our poor members ;) Also update the wording to clarify that it's not the menu command that goes on cooldown but toggling the break role.

2021-11-27 17:56 UTC, geisterfurz007 commented on src/programs/menu/break-handler/addBreak.ts
> +  state.ignoredGroupDMs.push(dmChannel.id);
Ignoring the DMs shouldn't be needed here; that was a hastily built thing to ignore incoming messages to YesBot while he was waiting for a naming suggestion (in the past any message would cause the menu to open) and is not relevant for reactions.

2021-11-27 17:56 UTC, geisterfurz007 commented on src/programs/menu/break-handler/addBreak.ts
> +      removeIgnore(dmChannel);
See above; this shouldn't be needed

2021-11-27 17:56 UTC, geisterfurz007 commented on src/programs/menu/break-handler/addBreak.ts
> +      removeIgnore(dmChannel);
See above; this shouldn't be needed

2021-11-27 17:56 UTC, geisterfurz007 commented on src/programs/menu/break-handler/break-role-events.ts
> +    await prisma.usersOnBreak.delete({ where: { userId: member.id } });
I feel like these two could cause problems or at least error messages because entries are created/deleted twice (picking the menu entry creates / deletes the entry and toggles the role causing the same action to be done again). Can we find a way to avoid that duplication (ideally one that doesn't involve just deleting the prisma calls in the menu items)?

2021-11-27 17:56 UTC, geisterfurz007 commented on src/programs/menu/break-handler/addBreak.ts
> +  if (reaction) {
Invert this if to reduce nesting and return statements.

2021-11-27 17:56 UTC, geisterfurz007 commented on src/programs/menu/break-handler/removeBreak.ts
> +  if (reaction) {
Invert if

2021-11-27 17:56 UTC, geisterfurz007 commented on src/programs/menu/break-handler/removeBreak.ts
> +  state.ignoredGroupDMs.push(dmChannel.id);
Not needed, see above.

2021-11-27 17:56 UTC, geisterfurz007 commented on src/programs/menu/break-handler/removeBreak.ts
> +      removeIgnore(dmChannel);
Not needed.

2021-11-27 17:56 UTC, geisterfurz007 commented on src/programs/menu/break-handler/removeBreak.ts
> +      removeIgnore(dmChannel);
Not needed.

2021-11-27 17:56 UTC, geisterfurz007 commented on src/programs/menu/break-handler/removeBreak.ts
> +import { UsersOnBreak } from "@yes-theory-fam/database/client";
Filename -> `remove-break.ts`

2021-11-27 17:56 UTC, geisterfurz007 commented on src/programs/menu/common.ts
> +    "Because of technical reasons I can only wait 60 seconds for a reaction. I removed the other message to not confuse you. If you need anything from me, just drop me a message!"
Having such a specific error message in a function with a very general name `handleError` might be dangerous. Maybe something like `handleReactionTimeout` might be a better fit?

2021-11-27 17:56 UTC, geisterfurz007 commented on src/programs/menu/common.ts
> +  return Date.now() - Number(userCoolDownTime) > twentyFourHours;
```suggestion
  return Date.now() - userCoolDownTime.getTime() > twentyFourHours;
```
(Assuming userCoolDownTime is `Date`); does the same but is more readable.

2021-11-27 17:56 UTC, geisterfurz007 commented on src/programs/menu/common.ts
> +};
This function reads a bit buggy (I didn't test it yet though) 🤔

The most drastic example for how this could go wrong is this: What happens if I provide an emoji that is not in the `allCollectedEmojis` array? The filter doesn't make use of it so it's never collected.

This could also go wrong if I pass emoji as something from the array and the user decides to pick some other option (or adds one themselves) in which case `undefined` will be returned (e.g. emoji === 🦥 and the user adds ✅; the function will try to find an item in the list of ✅ that is a 🦥 which doesn't exist, so undefined).

2021-11-27 17:56 UTC, geisterfurz007 commented on src/programs/menu/dm-menu.ts
> +    }
Given that we will want to stuff other things into the menu, defaulting to this seems a little drastic (what if a member wants to check their currency while on break for example).

Instead the code should always show all options and the sloth should function as a toggle.

2021-11-27 17:56 UTC, geisterfurz007 commented on src/programs/menu/nameChange.ts
> +import { Message, DMChannel } from "discord.js";
Filename -> `name-change.ts`

2022-02-20 12:11 UTC, geisterfurz007 requested changes

2022-02-20 12:11 UTC, geisterfurz007 commented on src/programs/menu/break-handler/add-break.ts
> +    return;
`return;` isn't needed here

2022-02-20 12:11 UTC, geisterfurz007 commented on src/programs/menu/break-handler/add-break.ts
> +    return;
`return;` isn't needed here

2022-02-20 12:11 UTC, geisterfurz007 commented on src/programs/menu/break-handler/remove-break.ts
> +    return;
`return;` isn't needed here

2022-02-20 12:11 UTC, geisterfurz007 commented on src/programs/menu/break-handler/remove-break.ts
> +    return;
`return;` isn't needed here

2022-10-07 07:37 UTC, hasanlatch007 commented
Closing this since it is too old, and will need to be updated, better start from scratch.

2022-10-07 07:37 UTC, closed without merging