fix: crash on DM errors
Yes-Theory-Fam/yesbot-ts pull request #594
Opened 2021-11-17 20:03 UTC by geisterfurz007

2021-11-17 20:41 UTC, hasanlatch007 reviewed
Shouldn't this also be awaited?
https://github.com/Yes-Theory-Fam/yesbot-ts/blob/0a984baff75b834badc768263354f90fb40e541e/src/programs/filter.ts#L24-L28

2021-11-18 22:33 UTC, geisterfurz007 commented
> Shouldn't this also be awaited?
> 
> https://github.com/Yes-Theory-Fam/yesbot-ts/blob/0a984baff75b834badc768263354f90fb40e541e/src/programs/filter.ts#L24-L28

Should indeed! Added a couple more async/awaits in the file, thanks!

2021-11-19 11:16 UTC, hasanlatch007 requested changes

2021-11-19 11:16 UTC, hasanlatch007 commented on src/programs/filter.ts
>          .then((dm) =>
```suggestion
                .then(async (dm) =>
          await dm.send(
```
This could still crash the bot if the message failed to send if the user has his DM privacy set to friends only

2021-11-19 13:04 UTC, hasanlatch007 commented on src/programs/filter.ts
>          .then((dm) =>
This was corrected to me on the Discord, thank you Michel!

2021-11-19 13:05 UTC, hasanlatch007 approved these changes
LGTM!

2021-11-19 13:05 UTC, merged