removed case sensitive requirement for commands...
Yes-Theory-Fam/yesbot-ts pull request #667
Opened 2022-02-22 12:22 UTC by joshtrivedi

... added toLowerCase() to command triggers, and voice on demand

2022-02-22 12:42 UTC, hasanlatch007 commented on src/event-distribution/events/message.ts
>    const split = message.content.split(" ");
```suggestion
  const split = message.content.toLowerCase().split(" ");
  const trigger = split[0];
  const subTrigger = split[1];
```
The way you've done is basically having it 50/50, any command send the trigger is lowerCased but not the subtrigger, for example `!group Join` would not work.

2022-02-22 12:47 UTC, hasanlatch007 requested changes
This actually breaks some of our commands, for example `!timeoutTimer`, it is a trigger with one capitalized letter, with the `toLowerCase()` in [src/event-distribution/events/message.ts](https://github.com/Yes-Theory-Fam/yesbot-ts/pull/667/files#diff-77b198c2b3d38af921c099137af5327d91540a4b70eac40f4391ab96d0de43d8) every message is extracted in lower case and won't be picked up by the new event handler system.

2022-02-23 04:31 UTC, joshtrivedi reviewed
reviewed, please verify

2022-02-23 12:34 UTC, hasanlatch007 commented on src/event-distribution/events/message.ts
> +  const subTrigger = split[1] ?? "";
` ?? ""` Is useless here.

2022-02-23 12:37 UTC, hasanlatch007 requested changes
This still breaks commands that have a capital letter like `!timeoutTimer` I would recommend to add this in [src/event-distribution/events/message.ts](https://github.com/Yes-Theory-Fam/yesbot-ts/pull/667/files#diff-77b198c2b3d38af921c099137af5327d91540a4b70eac40f4391ab96d0de43d8) at line `32` and `33`

```suggestion
  const trigger = options.trigger?.toLowerCase() ?? "";
  const subTrigger = options.subTrigger?.toLowerCase() ?? "";
```

2022-02-24 06:27 UTC, joshtrivedi commented on src/event-distribution/events/message.ts
> +  const subTrigger = split[1] ?? "";
that was in case there are no sub triggers, it was still passing null

2022-02-24 06:29 UTC, joshtrivedi reviewed
check again shawty

2022-02-25 07:03 UTC, joshtrivedi commented
something fails help

2022-02-25 07:20 UTC, geisterfurz007 commented
> something fails help

The testsuite creates snapshot files (basically taking the output, throwing it in a file and saving that) for various outputs of the event distribution. On subsequent testruns, the actual outputs are compared against the file and if the content doesn't match the new result, the test fails.  

Since the whole thing is now case insensitive, the output has changed (the triggers extracted from a message are now converted to lowercase, altering the HandlerInfo returned for some messages in the tests). You can update the tests using `yarn test -u` telling jest that the changes were intentional causing those snapshot files to be written again. Commit those and push them, then the pipeline should go green again 👍

2022-03-02 19:19 UTC, geisterfurz007 requested changes
During testing one interaction turned out to still be case-sensitive; the group ping isn't handled by a trigger but a general check if the message.content contains `@group` which currently is not case-insensitive.

A `.toLowerCase()` near the top of group-ping.ts should fix this.

After that, LGTM!

2022-03-04 18:02 UTC, hasanlatch007 commented on src/event-distribution/events/message.ts
> +  const subTrigger = split[1] ?? "";
I don't know if I would need it for when strictNullsCheck is enabled so Ill keep it.

2022-03-04 18:08 UTC, geisterfurz007 approved these changes
LGTM!

2022-03-04 18:09 UTC, hasanlatch007 approved these changes
Also LGTM!

2022-03-04 18:10 UTC, merged