Chore/refactor map
Yes-Theory-Fam/yesbot-ts pull request #676
Opened 2022-03-05 15:28 UTC by joshtrivedi

Just testing please dont ban

2022-03-06 00:16 UTC, geisterfurz007 requested changes

2022-03-06 12:04 UTC, geisterfurz007 requested changes

2022-03-06 12:04 UTC, geisterfurz007 commented on src/programs/map.ts
> +import { logger } from "./remote-control/add-reaction";
Unused import should be removed (sorry, missed that last night).

2022-03-07 09:53 UTC, joshtrivedi commented on src/programs/map.ts
> +import { logger } from "./remote-control/add-reaction";
lmfao on it

2022-03-07 12:36 UTC, joshtrivedi reviewed
LGTM?

2022-03-07 17:46 UTC, merged