Fix: Force ping needed groups
Yes-Theory-Fam/yesbot-ts pull request #708
Opened 2022-05-07 17:48 UTC by hasanlatch007

Probable fix for #551

2022-05-08 14:48 UTC, geisterfurz007 requested changes
This PR introduces several code duplications; there should be one function that takes in a group name and TextChannel and sends the group ping. As it stands now, code would have to be adapted thrice if for example the group ping message was to be adapted.

2022-05-08 15:24 UTC, hasanlatch007 commented
> This PR introduces several code duplications; there should be one function that takes in a group name and TextChannel and sends the group ping. As it stands now, code would have to be adapted thrice if for example the group ping message was to be adapted.

Damn i was hoping we'd ignore code duplication for this bug :') will rework it

2022-05-11 17:12 UTC, geisterfurz007 requested changes
The end of the group-ping logic can be replaced by this method as well:

https://github.com/Yes-Theory-Fam/yesbot-ts/blob/70690969451b9fc379efd41ab304223ee586cb07/src/programs/group-manager/user-commands/group-ping.ts#L116-L130

2022-05-20 19:35 UTC, geisterfurz007 approved these changes

2022-05-20 19:45 UTC, merged