feat: automatically add role "from strangers to friends"
Yes-Theory-Fam/yesbot-ts pull request #828
Opened 2022-10-25 17:39 UTC by L-390

2022-10-25 19:53 UTC, geisterfurz007 requested changes
This looks promising! I have a couple points on code-style and a couple minor nitpicks however :)

2022-10-25 19:53 UTC, geisterfurz007 commented on src/programs/strangers-to-friends.ts
> +  channelNames: ["from-strangers-to-friends"],
Prefer creating a new entry in `src/collections/chat-names.ts` over setting it as string here; that makes it easier for the future in case there might be new features in that channel (wink, wink, nudge, nudge).

2022-10-25 19:53 UTC, geisterfurz007 commented on src/programs/strangers-to-friends.ts
> +    let users = message.mentions?.members;
Prefer `const` for values that don't change

2022-10-25 19:53 UTC, geisterfurz007 commented on src/programs/strangers-to-friends.ts
> +    users?.forEach((user: GuildMember) => {
Prefer a for-of loop over array foreach (arguably, this is very subjective but for-of is used in pretty much the entirety of YesBot's codebase, so I'd rather see it used here as well); you can use something like `if (!users) return;` on a line above that then to avoid iterating over undefined / null.

2022-10-25 19:53 UTC, geisterfurz007 commented on src/programs/strangers-to-friends.ts
> +      if (user.roles?.cache.has("499143174271270913")) {
Don't hardcode the roleid; that makes code impossible to test on testservers. Instead, look up the role by name (there is `Tools.getRoleByName` in `src/common/tools.ts`) when the handler is run.

2022-10-25 19:53 UTC, geisterfurz007 commented on src/programs/strangers-to-friends.ts
> +      } else {
An empty if block is better expressed by inverting the condition and moving the else logic there:

```ts
if (something) {}
else { console.log('Some code here'); }
```
is equal to
```ts
if (!something) { console.log(`Some code here`); }
```

2022-10-25 19:53 UTC, geisterfurz007 commented on src/programs/strangers-to-friends.ts
> +        return;
`return;` as last statement in a function is unnecessary.

2022-10-26 16:59 UTC, L-390 commented
Hope I didn't forget any of your suggestsion :)

2022-10-27 15:14 UTC, geisterfurz007 requested changes
Two more little nitpicks but then we should be good!

2022-10-27 15:14 UTC, geisterfurz007 commented on src/programs/strangers-to-friends.ts
> +      "From Strangers To Friends :camera:",
The emoji must be a literal emoji

```suggestion
      "From Strangers To Friends 📸",
```

2022-10-27 15:14 UTC, geisterfurz007 commented on src/programs/strangers-to-friends.ts
> +        user.roles.add(role.id);
`await` asynchronous function calls so errors are caught in the event handler and don't bubble up to crash the bot.

```suggestion
        await user.roles.add(role.id);
```

2022-10-27 17:40 UTC, geisterfurz007 approved these changes
LGTM! Thanks a bunch!

2022-10-27 17:42 UTC, merged