[WIP] Approve shoutout tickets
Yes-Theory-Fam/yesbot-ts pull request #966
Opened 2023-03-24 20:45 UTC by christolis

Resolves issue #720.

### Things to do
- [ ] Automatically remove permissions once the privileged user posts a message in the shoutouts channel.
- [ ] Implement a system so that privileged users lose the permission to post a message after a day.
- [ ] Improve the messages sent by the bot so that they fit more with what the Yes Theory Bot would send (will probably need external input on this).
- [ ] *(maybe)* Think about an efficient way to detect the user who opened the ticket from the ticket text channel instead of manually inputting it as an argument.

2023-03-25 09:38 UTC, christolis commented
Hey @geisterfurz007, which role(s) should allow users to execute the command? 🤔

2023-03-25 11:09 UTC, geisterfurz007 commented
@christolis the permissions for slash commands can be configured directly in Discord (Server Settings > Integrations > Your Bot), so you don't have to worry about that :)

2023-03-26 11:25 UTC, christolis commented
Good day @geisterfurz007! As for this task:
> _(maybe)_ Think about an efficient way to detect the user who opened the ticket from the ticket text channel instead of manually inputting it as an argument.

Do you think we should rename individual shoutout tickets to a format like `#shoutout-{userId}` instead of `#shoutout-{usernametag}` in order to reduce the /shoutout command to `/shoutout toggle` and automatically get the target user depending on where the command was executed? Or should we leave it as it is?

Also, whenever you have time (or if anybody else can help me with it), I'll need some help implementing this:
> Improve the messages sent by the bot so that they fit more with what the Yes Theory Bot would send (will probably need external input on this).

2023-03-26 11:37 UTC, geisterfurz007 commented
> Do you think we should rename individual shoutout tickets to a format like `#shoutout-{userId}` instead of `#shoutout-{usernametag}`

Yes, absolutely! That also fixes a (fairly uncommon but still possible) bug where someone can change their username while having a ticket open and having more than one ticket open at a time and it removes the need for sanitizing the username/tag.

Regarding the messages: Is this only regarding phrasing? If yes, feel free to put any text that you feel is reasonably polite and to the point; I will go through the texts during review again either way. If not, I am not sure I understand what you mean.

2023-04-06 12:33 UTC, geisterfurz007 requested changes
For a first run, this already looks really nice, good job! A couple comments though; if you have any questions on them, let me know!

2023-04-06 12:33 UTC, geisterfurz007 commented on src/programs/shoutout-perms.ts
> +    const sendPerms = getSendPerms(shoutouts, user);
Earlier I mentioned removing the getSendPerms in favour of a shorter deletePerms function; since this is the only place where we actually want to know if that user has those permissions, we can check it with this:
```ts
const perms = await shoutouts.permissionsFor(user);
const hasSendPerms = perms?.has(PermissionsBitField.Flags.SendMessages) ?? false;
```

2023-04-06 12:33 UTC, geisterfurz007 commented on src/programs/shoutout-perms.ts
> +const logger = createYesBotLogger("shoutouts", ShoutoutTimer.name);
The logger is unused and can be removed

2023-04-06 12:33 UTC, geisterfurz007 commented on src/programs/shoutout-perms.ts
> +      deletePerms(user.id, sendPerms);
returned `Promise`s *must* be awaited; since Node 16 any errors that comes up in a Promise that doesn't have either a `.catch` or an `await` inside a `try/catch` will terminate the process. All handlers are wrapped in `try/catch` somewhere deep in the "core" of YesBot but for that to work, `await` is needed.
```suggestion
      await deletePerms(user.id, sendPerms);
```

2023-04-15 20:35 UTC, geisterfurz007 requested changes
Cheeky copy-paste bug hid itself :)

2023-04-15 20:35 UTC, geisterfurz007 commented on src/programs/shoutout-perms.ts
> +      await channel.permissionOverwrites.delete(user);
```suggestion
      await shoutouts.permissionOverwrites.delete(user);
```

2023-04-15 20:40 UTC, geisterfurz007 approved these changes
LGTM! Thanks a lot for the contribution! The team will be happy to not need to click through 5 menus again when dealing with shoutouts :)

2023-04-15 20:41 UTC, merged

2023-04-15 20:43 UTC, christolis commented
I'm glad that that's the case! I'd love to work on more issues and things that you guys might want added to the project! 😇