[WIP] Automate Nitro Booster monthly cleanup
Yes-Theory-Fam/yesbot-ts pull request #974
Opened 2023-04-20 20:21 UTC by christolis

2023-04-20 20:38 UTC, christolis commented on src/programs/nitro-colors.ts
> +    const TEST_CRON = "*/1 * * * *"; // Every 1 minute, for testing purposes
@geisterfurz007 I have a feeling that this could be improved by automatically picking `TEST_CRON` depending on whether the bot is running in a test server or not (as far as I remember, there are some environment variables that could possibly help with this). What do you think?

2023-06-25 16:31 UTC, geisterfurz007 commented on src/programs/nitro-colors.ts
> +    const TEST_CRON = "*/1 * * * *"; // Every 1 minute, for testing purposes
Sorry, this took ages for me to get to! Yes, you can rely on `process.env.NODE_ENV` to have the value `"production"` when built for production. By default it has the value `"development"` and when the tests are running it has the value `"test"`. So easiest to test on `process.env.NODE_ENV === "production"` to determine which schedule to use!

2023-06-25 16:40 UTC, geisterfurz007 requested changes

2023-06-25 16:40 UTC, geisterfurz007 commented on src/programs/nitro-colors.ts
> +        .then((messages) => {
There is a lot of nesting going on here; instead of using `.then()`, use `await` to avoid deeply nested callbacks.

2023-06-25 16:40 UTC, geisterfurz007 commented on src/programs/nitro-colors.ts
> +        });
Avoid placing `async` code inside of `forEach`; the promises inside are "dangling" and rejections inside of them are uncaught. Instead either use a `for-of` loop, or `.map` an array of values to an array of promises and then use `await Promise.all()` to ensure all errors are handled inside the correct callstack.

2023-06-25 16:40 UTC, geisterfurz007 commented on src/programs/nitro-colors.ts
> +              "@Nitro Booster It is time to pick a new color for the new month!",
I am not sure if this ping here would work (since the API has no chance of knowing where the role name ends). You can use `Tools.getRoleByName("Nitro Booster", guild)` to get the actual role and use that in the string `${boosterRole} It is time [...]` which should yield a proper ping.

2023-06-25 16:40 UTC, geisterfurz007 commented on src/programs/nitro-colors.ts
> +export class RoleResetCron {
To avoid this file getting *huge* (my usual limit is around 150 lines), it's cleaner to create a new folder called `nitro-colors`, move this new reset logic in a separate file into that folder and rename *this* file to something sensible and move it in there as well.

2023-06-25 16:42 UTC, geisterfurz007 commented
I also think it makes sense to also include some logic for editing the roles between seasons to avoid pinging people when that change hasn't been made yet by a moderator. Let me know if that's something you'd like to do in this PR as well; if it is, I can pass you the list of color codes and names here (it won't take two months this time, I hope!).

2023-06-25 19:00 UTC, christolis commented on src/programs/nitro-colors.ts
> +        .then((messages) => {
Done!

2023-06-25 19:01 UTC, christolis commented on src/programs/nitro-colors.ts
> +              "@Nitro Booster It is time to pick a new color for the new month!",
Should be fixed with the newest commits! 🙌

2023-06-25 19:06 UTC, christolis commented on src/programs/nitro-colors.ts
> +    const TEST_CRON = "*/1 * * * *"; // Every 1 minute, for testing purposes
Don't worry about it! I did end up using `process.env.NODE_ENV` to control which cron expression to use, and it appears to be working perfectly!

2023-06-25 19:17 UTC, christolis commented on src/programs/nitro-colors.ts
> +        });
Thank you for the suggestion! I will keep this in mind next time I need to deal with asynchronous code inside `forEach` loops. It should be changed now!

2023-06-25 19:38 UTC, christolis commented on src/programs/nitro-colors.ts
> +export class RoleResetCron {
Done! I renamed the original file to `index.ts`.

2023-06-25 19:42 UTC, christolis commented
> I also think it makes sense to also include some logic for editing the roles between seasons to avoid pinging people when that change hasn't been made yet by a moderator. Let me know if that's something you'd like to do in this PR as well; if it is, I can pass you the list of color codes and names here (it won't take two months this time, I hope!).

Sure thing! Although, along with the list of the color codes and names, could you please provide a more detailed explanation of how this will work?

2023-06-27 17:49 UTC, geisterfurz007 commented
> Sure thing! Although, along with the list of the color codes and names, could you please provide a more detailed explanation of how this will work?

Absolutely! For each (northern hemisphere) season, we have 5 shades of the same colors red, green, yellow, blue and orange. Winter colours are available from December to February, Sprint from March to May, Summer from June to August and Autumn from September till November (all ranges inclusive).

So essentially, at the start of the month, remove everyone's roles, check if it's time for new colours, if yes, update the names and colors of the five roles, if not, leave them untouched. Then once that is finished, post the message in the channel that new stuff is available.

Colours in JSON because that's possibly easiest to make use of:

```json
{
  "summer": {
    "red": { "name": "Icecream", "color": "#e0234a" },
    "green": { "name": "Meadow", "color": "#08bd56" },
    "yellow": { "name": "Sunshine", "color": "#e0d41a" },
    "blue": { "name": "Cloudless", "color": "#0fbdb5" },
    "orange": { "name": "Beachball", "color": "#ff491f" },
  },
  "autumn": {
    "red": { "name": "Bonfire", "color": "#cf453a" },
    "green": { "name": "Overgrown", "color": "#7ba702" },
    "yellow": { "name": "Pumpkin", "color": "#dfac3a" },
    "blue": { "name": "Moonshine", "color": "#1a8391" },
    "orange": { "name": "Foliage", "color": "#d1652b" },
  },
  "winter": {
    "red": { "name": "Candlelight", "color": "#b10f0a" },
    "green": { "name": "Pinetree", "color": "#1a7248" },
    "yellow": { "name": "Cinnamon", "color": "#ffaa00" },
    "blue": { "name": "Nighttime", "color": "#2c6c9e" },
    "orange": { "name": "Clementine", "color": "#df5b06" },
  },
  "spring": {
    "red": { "name": "Veronika 👝", "color": "#feaeac" },
    "green": { "name": "Pear 🍐", "color": "#7dd17d" },
    "yellow": { "name": "Citrus 🍋", "color": "#efef7b" },
    "blue": { "name": "Soda 💧", "color": "#a9ccff" },
    "orange": { "name": "Shrimp 🦐", "color": "#ffb066" },
  },
}
```

If you have any questions, let me know!

2023-06-28 06:54 UTC, christolis commented
Awesome! A few questions though:
- I noticed that there are emojis only in the roles that belong in the `spring` category. Is this intentional?
- Should the announcements be different for when the roles have changed due to the new season and for when a new month is around, or should it be the same regardless of the scenario?
- I was thinking of creating a `nitro-roles.ts` file in `collections/` and storing all the different Nitro roles from the JSON above in there. Should this be the approach to take or is there a better one?

2023-06-28 07:06 UTC, geisterfurz007 commented
1. Yes, at least that's how I found them in the list that Josh keeps.

2. Good point! Yeah, if you want, you can vary them (maybe also one like "Last chance for these colours this year" for the last month of a season?)!

3. I think such a file might make sense but I'd rather keep it together with the rest of the nitro stuff in the folder under programs; the corrections directory is an old relic that I would love to get rid of in the long run. Keeping features together in one folder makes the editing experience nicer, imo, because you don't need that many folders open at once.

2023-07-12 12:05 UTC, geisterfurz007 requested changes

2023-07-12 12:05 UTC, geisterfurz007 commented on src/programs/nitro-colors/roles-reset.ts
> +        });
This is only sent for a new season; it should be sent for each new month.

2023-07-12 12:05 UTC, geisterfurz007 commented on src/programs/nitro-colors/roles-reset.ts
> +    cron.schedule(CRON, async () => {
This anonymous function is very large possibly making it hard to follow each step; instead of commenting each section of code describing what it does, you can extract them into smaller functions each with their respective name describing their function. This has several benefits including reducing indentation and making it easier to use editor features like jumping to each bit of code and collapsing unneeded sections.

2023-07-12 12:22 UTC, christolis commented on src/programs/nitro-colors/common.ts
> +}
Good catch! I made them `const`. When writing the code, I thought it wouldn't matter initially, but on second thought, these need to be declared as constant.

2023-07-12 12:45 UTC, christolis commented on src/programs/nitro-colors/roles-reset.ts
> +        });
Fixed! 🚀

2023-07-12 13:18 UTC, christolis commented on src/programs/nitro-colors/roles-reset.ts
> +    cron.schedule(CRON, async () => {
Done! ✅

2023-07-12 14:06 UTC, geisterfurz007 approved these changes
LGTM!

This is great and will save us a lot of clicking and stuff! Thanks so much!

2023-07-12 14:09 UTC, geisterfurz007 commented
Also sorry for all the delays in the reviews and thanks for your patience. I really appreciate it!

2023-07-12 14:20 UTC, christolis commented
> Also sorry for all the delays in the reviews and thanks for your patience. I really appreciate it!

No worries! I’m just really glad to be helping with getting these features made. I’d love to work on some more, if there are any! 🙌

2023-07-12 14:27 UTC, merged